### PR TITLE
#909 and #355 - Exporting and NRT

### PR DESCRIPTION
**Pull request by squaregoldfish**
This is a big pull request the covers export and NRT data handling capabilities. I know it's really too big, but the development of the two in parallel kind of got tangled together and the two branches rely on each other to some extent.

Main features are:

* Workflow for data sets: added steps for ICOS verification and approval. Steps are now:
  * Extraction, Data Reduction and Automatic QC as now
  * User QC
  * User submits for expert review
  * Expert approves dataset for export
* Export API and scripts to discover exportable datasets, export them and (eventually) submit them to Carbon Portal, SOCAT etc. The scripts are still in development but the API is solid.
* NRT data. API and scripts for:
  * Retrieve files from initial sources (IMAP email only so far) and upload them to a local FTP server
  * Transfer from FTP into QuinCe
  * Create NRT data set

NRT datasets have a special status in QuinCe - users can create a new dataset on top of them (which destroys the NRT dataset). NRT datasets are marked as ready for export as soon as automatic QC is complete (no verification required).

Eventually NRT datasets should be read only (i.e. no user QC allowed) - that will come in a future PR.

### CODE REVIEW

**Comment by jonasfh** [comment]
**Doc build script:** 
```
 $ ./Documentation/Design/ExportScripts/build.sh 
./Documentation/Design/ExportScripts/build.sh: line 11: pandoc: command not found
```
...do I need to install pandoc? mermaid?

**API**
* In file WebApp/src/uk/ac/exeter/QuinCe/api/export/CompleteExport.java: Why is this a POST-request? Would expect this to be GET
* You should probably just remove the api/test - folder

Non - essentials: 
- Whitespaces at end of lines in Documentation/Design/ExportScripts/ExportScripts.md
- Replace author zuj007 with Steve Jones :)

**Comment by jonasfh** [comment]
Regarding issue #355 
================

I think it would be beneficial to use virtualenv and pip to manage python. This way you can ensure a consistent environment with the correctly installed packages for testing. Makes it much easier for "the next guy". How I did it for the glodap-project: 

```
# Install pip, depending on OS
# sudo apt-get install pip
# install virtualenv
python -m pip install --user virtualenv
# Set up virtual environment in .env, in the current folder
virtualenv -p python3 --no-site-packages .env
# To activate the new environment in your current console: 
source .env/bin/activate
# Install neccessary python packages from requirements.txt - file: 
pip install -r requirements.txt
```
After activation, requirements are only installed in this virtual environment, not globally on your machine.

**Comment by jonasfh** [comment]
Regarding issue #355 
================

Error: in quince.py line 19: `instruments = conn.read()` returns a binary string. Resolved by using: `instruments = conn.read().decode("utf-8")`

When running `configure_nrt.py`, the order of the configuration elements are random.

Emails are sometimes left in the folder, randomly picked up later? 

** Details **
- Docs Documentation/Design/NearRealTime/NearRealTime.md has a mix of tabs and spaces in the json - section
- Nice general documentation, but I would love to see a simple Usage - section with requirements etc.

**Comment by jonasfh** [comment]
There is an issue if you just quit after starting configure_nrt: 
nrt_configure-error

**Comment by squaregoldfish** [comment]
> # Regarding issue #909
> **Doc build script:**
> 
> ```
>  $ ./Documentation/Design/ExportScripts/build.sh 
> ./Documentation/Design/ExportScripts/build.sh: line 11: pandoc: command not found
> ```
> ...do I need to install pandoc? mermaid?
> 
We should revisit this to decide what the best form of documentation is to use as close to a universal Markdown system as possible. Pandoc is pretty widely used, but requiring other extensions might be going too far.

> **API**
> 
> * In file WebApp/src/uk/ac/exeter/QuinCe/api/export/CompleteExport.java: Why is this a POST-request? Would expect this to be GET

Remains as a POST, because it's telling QuinCe that we've successfully completed our exporting work and the dataset's status can be updated.

> * You should probably just remove the api/test - folder

Done.

> 
> Non - essentials:
> 
> * Whitespaces at end of lines in Documentation/Design/ExportScripts/ExportScripts.md
> * Replace author zuj007 with Steve Jones :)

Done

**Comment by squaregoldfish** [comment]
> # Regarding issue #355
> Error: in quince.py line 19: `instruments = conn.read()` returns a binary string. Resolved by using: `instruments = conn.read().decode("utf-8")`
> 

This seems to work in Python 3.7+ but it doesn't do any harm to add it so I have

> When running `configure_nrt.py`, the order of the configuration elements are random.
> 

This works in Python 3.7+ - we'll make this the required version

> Emails are sometimes left in the folder, randomly picked up later?
> 

This is behaving as designed - if a matching file from an email already exists on the FTP server the email is skipped and processed next time.


> ** Details **
> 
> * Docs Documentation/Design/NearRealTime/NearRealTime.md has a mix of tabs and spaces in the json - section

Fixed

> * Nice general documentation, but I would love to see a simple Usage - section with requirements etc.

The documentation was mostly written to get my ideas on paper, and not for general usage. I've created issues for creating installation and setup documentation for QuinCe and the export/NRT infrastructure. We'll be able to write good versions of these once the Docker/Virtual Environments are settled in and working.

**Comment by squaregoldfish** [comment]
The comment regarding using a virtual environment for the python scripts has also been turned into its own issue (#1053)

**Pull request merged**
