### PR TITLE
(#1089) New sensors configuration

### LINKED ISSUE #826: Handling Required Groups as multiple sensors
We currently aim to handle multiple sensors of the same type in special ways, so the sensors can be individually QCed (#576, #722) and have averaging/fallback as required.

This functionality should be extended to Required Groups, so (eg) Absolute and Differential Equilibrator Pressure are treated as multiple sensors of the same type.

There are two ways this might be implemented:
1. The members of the Required Groups are 'combined' at data extraction time, as a special step alongside combining multiple sensors of the same type
2. We eliminate the concept of a Required Group, and have a single Equilibrator Pressure with a question asking whether it's differential or absolute (in the former case, an atmospheric pressure is then required). We can do this with the Depends Questions, as per xCO₂ and xH₂O.

2 is currently my favourite option.

### LINKED ISSUE #1089: New sensor configuration
This issue will develop a new sensor configuration that will be the basis for allowing multiple variables in QuinCe.

### PR DESCRIPTION
**Pull request by squaregoldfish**
The sensor configuration has been moved into the database. It uses the following new tables:

* `sensor_types` - holds all the different types of sensor that the system knows about
* `variables` - the different core variables that the system can calculate (marine pCO2 is the only one so far, but we'll add atmospheric pCO2, pH etc.)
* `variable_sensors` - the sensors required for a given variable
* `instrument_variables` - the variables that a given instrument can measure

At this stage the minimum code changes have been made to work with the new database structure. Things like specifying which variables an instrument measures are still hard coded, and there's a lot of other places where the code will be rewritten as more parts of the planned database changes are implemented. I've tried to mark those with TODO comments but I've probably missed some. QC flags may not be calculated quite correctly either, but that's going to be rewritten later on anyway.

The user interface hasn't changed except in some cosmetic ways (the order of listed sensors, and all sensors can have calibrations applied automatically). Everything should work exactly as it always did.

There's a whole stack of junit tests for the new database structure and the logic surrounding it.

Close #1089 
Close #826

### CODE REVIEW

**Comment by jonasfh** [comment]
There are some errors from the Flyway migration task: 

> Task :flywayMigrate
> DB: Unknown table 'quince_dev.instrument_variables' (SQL State: 42S02 - Error Code: 1051)
> DB: Unknown table 'quince_dev.variable_sensors' (SQL State: 42S02 - Error Code: 1051)
> DB: Unknown table 'quince_dev.variables' (SQL State: 42S02 - Error Code: 1051)
> DB: Unknown table 'quince_dev.sensor_types' (SQL State: 42S02 - Error Code: 1051)
> DB: No data - zero rows fetched, selected, or processed (SQL State: 02000 - Error Code: 1329)

However, this seems to be warnings: The first four from the DROP TABLE IF EXISTS - statements where tables don't exist. The last one is probably trying to migrate data where there is none.

**Comment by squaregoldfish** [comment]
Fix tests:

* ResourceManager tests need to be flyway-based now the sensors config is in the database.
* SensorConfigTests: Don't hard-code the variable IDs, but look them up from the database in case the ID counter isn't stable.

**Comment by squaregoldfish** [comment]
Hopefully the tests are fixed now. We have to be very careful about setting up and tearing down between tests and test classes.

**Comment by jonasfh** [comment]
There is an issue assigning Run Type column for an instrument. Running git bisect it seems the error is introduced in the following commit: 

> da010d07e91d64033d76c13a702f35be997f2dab is the first bad commit
> commit da010d07e91d64033d76c13a702f35be997f2dab
> Author: Steve Jones <steve@squaregoldfish.co.uk>
> Date:   Thu Feb 28 14:48:47 2019 +0100
>
>    (#1089) Fixed adding new instrument
>
> :040000 040000 17cf4e08b9afd338191e39091539605d90fae11c a27fcf8d722fa57e978f736855f7fcca3aa91ad2 M	WebApp

**Pull request closed without merging**
