### PR TITLE
Fixed up a Locale issue in the StringUtils.java file

### PR DESCRIPTION
**Pull request by glncstll**

### CODE REVIEW

**Review by squaregoldfish — CHANGES_REQUESTED** [review]
You have a strange QuinCe directory that you've checked in, which shouldn't exist. Remove it from your system, commit the changes and push them to Github. The pull request will update with the changes.

**Comment by glncstll** [comment]
so is that fine or not?

**Comment by squaregoldfish** [comment]
Screenshot 2022-10-27 at 08 13 04

This is the view of your repository, with the folder that needs to be removed. Since the actual change is only one line, it might be easier to roll back all your commits and start again, with just that one change.

**Comment by glncstll** [comment]
but I have already deleted everything and did from scratch
git clone git@github.com:glncstll/QuinCe.git
and after did the commit
that directory is again there created automatically from the system, inside there is 
carolinacantoni@MacBook-Air-di-Carolina QuinCe % pwd
/Users/carolinacantoni/Desktop/QuinCe-clone/QuinCe/QuinCe
carolinacantoni@MacBook-Air-di-Carolina QuinCe % ls
gradle		gradlew		gradlew.bat	lib		settings.gradle
carolinacantoni@MacBook-Air-di-Carolina QuinCe %

**Comment by glncstll** [comment]
i will try to roll back commits

**Comment by glncstll** [comment]
closed request

**Pull request closed without merging**
