### PR TITLE
(#133) Remove scrollable attribute to make tables resize nicely

### PR DESCRIPTION
**Pull request by jonasfh**
Add a min-height style to the pageTable class, so page is still layed out nicely

### CODE REVIEW

**Comment by jonasfh** [comment]
I don't think the scrollable-attribute adds improved usability anyway: It it generally easier to scroll the whole page, than having an internal box with a scrollbar on the page.

**Comment by squaregoldfish** [comment]
I would disagree - important parts of the page (table column headers, New Dataset/Upload Files buttons etc) should always be visible. Making the table scrollable takes makes that happen, if we just resize the table to make sure it takes up maximum space without pushing those off-screen.

**Comment by jonasfh** [comment]
I understand your points, but I disagree that they apply:

In general using the internal scrollbar is quite bad for usability. You need to scroll having the mouse in the right position, and scrolling with the keyboard is difficult. We don't have much functionality on the pages, and the New Data Set (and other) - buttons should rather be situated at the top of the table than below, this would definitely make for a nicer user experience. We could consider fixing the menu on the top of the page, so it stays when scrolling, but for the time being this is not necessary as nobody has this much data,

**Comment by jonasfh** [comment]
Moved the controls to above the table, for better usability when the table gets big.

**Comment by squaregoldfish** [comment]
Looks good. Merge it!

**Pull request merged**
